use_frameworks!

platform :ios, '9.0'

target 'ZWLogin_Example' do
  pod 'ZWLogin', :path => '../'
  pod 'ZWNetworking', :path => '../../ZWNetworking'

  target 'ZWLogin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
